### ISSUE TITLE
about params overwrite

### ISSUE THREAD

**Issue by Light--** [edmBernard/mxnet_example_shared_weight#3]
in ``` demo_shared_full_net.py```, you made a comment； ```# Making sure that fit doesn't always overwrite parameters by returning to module 1```, i have some small questions:

1. the params here means the model weights of two shared siamese network? 
2. how did you make sure of ``` not always overwrite ```?  just train model1, train model2 then train model1 again will make sure?

**Comment by edmBernard** [comment]
1. yeah in MXNet the parameter file contains weights
2. I don't remember exactly what I want to say, sorry 

btw, I advice you to use the Gluon API in MXNet. 3 years ago it was still new but now it the recommended way to implement network in MXNet. 
The Gluon API is more flexible and allow shared weight without difficulties.
